# Generated by Django 2.2.15 on 2020-08-05 13:57

from django.db import migrations
from django.db.models import Func, F


def backfill_hashed_guids(apps, schema_editor):
    AddonGUID = apps.get_model("addons", "AddonGUID")
    AddonGUID.objects.filter(hashed_guid=None).update(
        hashed_guid=Func(F("guid"), 256, function="SHA2")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("addons", "0019_auto_20200805_1350"),
    ]

    operations = [
        migrations.RunPython(backfill_hashed_guids),
    ]
